---
name: Test the validation pipeline reusable workflow on a self-hosted runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test-val-pipeline-self-hosted-aragog:
    uses: ./.github/workflows/val-pipeline-self-hosted.yaml
    with:
      target: aragog
      report_pkg_dir: ./tests/packages/aragog
